name: Replace
on:
  push:
    paths:
      - ".github/workflows/replace.yml"
jobs:
  replace-text:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Replace text
        shell: bash
        run: |
          declare -A replacements=(
            ["flt.user(BANNED_USERS)"]="BANNED_USERS"
            ["flt.user(SUDOERS)"]="SUDOERS"
          )

          for key in "${!replacements[@]}"; do
            find . -type d -name ".git" -o -path "./.github/*" -prune -o \
      -type f -name "*.py" -o -name "*.yml" \
            -exec sed -i "s|$key|${replacements[$key]}|g" {} +
          done

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Replace"
          commit_options: "--no-verify"
          repository: .
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

      - uses: Mattraks/delete-workflow-runs@v2
        with:
          delete_workflow_pattern: "Replace"
          keep_minimum_runs: 0
          retain_days: 0